### PR TITLE
added nix flake for nix support. 

### PR DESCRIPTION
**Pull request by Codespace0x25**
i added a nix flake for any one on nix to use it.

### CODE REVIEW

**Review by collinalexbell — APPROVED** [review]

**Comment by collinalexbell** [comment]
I merged it, but you really shouldn't PR distribution files like this if you haven't tested them.

**Comment by Codespace0x25** [comment]
noted

**Comment by dmyTRUEk** [comment]
Why was it reverted (b908ed4)?

**Comment by collinalexbell** [comment]
It wasn't tested.

**Pull request merged**
